# Generated by Django 2.2a1 on 2019-03-12 13:55

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190312_1259'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
